config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IQSS/dataverse:
      branch: develop
      repo: http://github.com/IQSS/dataverse
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IQSS/dataverse git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-indigo-woodlouse.sh
        container: qc.acc_snippy-russet-frog
  QC.Doc:
    repos:
      github.com/IQSS/dataverse find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-ecru-shark.sh
        container: qc.doc_geeky-heliotrope-lemur
      github.com/IQSS/dataverse git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ecru-opossum.sh
        container: qc.doc_skinny-chestnut-impala
      github.com/IQSS/dataverse markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-scarlet-wallaby.sh
        container: qc.doc_hazy-chestnut-penguin
      github.com/IQSS/dataverse restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-aqua-baboon.sh
        container: qc.doc_lousy-lime-weasel
  QC.Lic:
    repos:
      github.com/IQSS/dataverse licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-rose-tortoise.sh
        container: qc.lic_sleazy-champagne-gecko
  QC.Sec:
    repos:
      github.com/IQSS/dataverse bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-tan-angelfish.sh
        container: qc.sec_slaphappy-ivory-sponge
  QC.Sty:
    repos:
      github.com/IQSS/dataverse checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-seashell-husky.sh
        container: qc.sty_flabby-teal-dormouse
      github.com/IQSS/dataverse flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-corn-tarsier.sh
        container: qc.sty_hazy-violet-dogfish
      github.com/IQSS/dataverse hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-copper-hare.sh
        container: qc.sty_gimpy-pear-hare
      github.com/IQSS/dataverse jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tomato-monkey.sh
        container: qc.sty_leaky-cream-crane
      github.com/IQSS/dataverse rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sangria-wolfhound.sh
        container: qc.sty_bluesy-chocolate-sheep
      github.com/IQSS/dataverse stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-orchid-boar.sh
        container: qc.sty_homely-saffron-mist
  QC.Ver:
    repos:
      github.com/IQSS/dataverse get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-xanthic-ferret.sh
        container: qc.ver_muzzy-brown-chimpanzee
timeout: 1800
