config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IQSS/dataverse:
      branch: develop
      repo: http://github.com/IQSS/dataverse
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IQSS/dataverse git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-orchid-gopher.sh
        container: qc.acc_silly-ivory-hedgehog
  QC.Doc:
    repos:
      github.com/IQSS/dataverse find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-orange-dachshund.sh
        container: qc.doc_wimpy-smalt-chimpanzee
      github.com/IQSS/dataverse git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-turquoise-capybara.sh
        container: qc.doc_crabby-viridian-hare
      github.com/IQSS/dataverse markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-platinum-discus.sh
        container: qc.doc_pokey-periwinkle-dugong
      github.com/IQSS/dataverse restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-tangerine-swan.sh
        container: qc.doc_wheezy-champagne-dolphin
  QC.Lic:
    repos:
      github.com/IQSS/dataverse licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-black-millipede.sh
        container: qc.lic_messy-pumpkin-dingo
  QC.Sec:
    repos:
      github.com/IQSS/dataverse bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-green-numbat.sh
        container: qc.sec_hilly-peach-frog
  QC.Sty:
    repos:
      github.com/IQSS/dataverse checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-brown-grouse.sh
        container: qc.sty_ugly-lilac-tapir
      github.com/IQSS/dataverse flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-razzmatazz-burmese.sh
        container: qc.sty_zippy-lemon-swan
      github.com/IQSS/dataverse hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-dachsbracke.sh
        container: qc.sty_cheeky-crimson-monster
      github.com/IQSS/dataverse jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-magnolia-lion.sh
        container: qc.sty_hilly-cornflower-oyster
      github.com/IQSS/dataverse rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-blue-rattlesnake.sh
        container: qc.sty_gimpy-brown-uakari
      github.com/IQSS/dataverse stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-seashell-fish.sh
        container: qc.sty_snazzy-carmine-urchin
  QC.Ver:
    repos:
      github.com/IQSS/dataverse get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-horse.sh
        container: qc.ver_clammy-persimmon-frigatebird
timeout: 1800
